baseURL = "https://ayurveda-kerala.de/"
languageCode = "de-de"
title = "Ayurveda Kerala"

[pagination]
  pagerSize = 5

[params]
  googleAnalytics = "AW-17574288605"
  favicon = "/images/favicon.ico"
  defaultImage = "/images/hero-backwaters.jpg"
  twitter = "https://twitter.com/ayurvedakerala"
  facebook = "https://www.facebook.com/ayurvedakerala"
  instagram = "https://www.instagram.com/ayurvedakerala"
  email = "sebastiantinu@gmail.com"

[params.whatsapp]
  number = "49123456789"


[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"


[outputs]
  home = ["HTML", "RSS", "SITEMAP", "ROBOTS"]

[minify]
  minifyOutput = true

  [[menu.footer]]
    name = "Impressum"
    url = "/impressum/"
    weight = 20
